backend:
  name: git-gateway
  branch: main

media_folder: "images" # folder where your images are stored
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
